package cn.edu.wtc.ollama.service;

import cn.edu.wtc.ollama.model.Conversation;
import org.springframework.stereotype.Component;
import java.util.Collection;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

@Component
public class SessionManager {
    private final Map<String, Conversation> sessions = new ConcurrentHashMap<>();

    // 线程本地变量，用于暂存当前请求中实际使用的 sessionId
    private static final ThreadLocal<String> CURRENT_SESSION_ID_HOLDER = new ThreadLocal<>();

    /**
     * 获取或创建会话
     * @param sessionId 前端传入的ID (可为null)
     * @param model 模型名称
     * @return Conversation 对象
     */
    public Conversation getOrCreateSession(String sessionId, String model) {
        boolean isAutoGenerated = false;

        if (sessionId == null || sessionId.trim().isEmpty()) {
            sessionId = "auto_" + UUID.randomUUID().toString().replace("-", "");
            isAutoGenerated = true;
            System.out.println("⚠️ 检测到 sessionId 为空，已自动生成: " + sessionId);
        }

        if (model == null || model.trim().isEmpty()) {
            throw new IllegalArgumentException("模型名称不能为空");
        }

        CURRENT_SESSION_ID_HOLDER.set(sessionId);

        return sessions.computeIfAbsent(sessionId, id -> new Conversation(id, model));
    }

    /**
     * 获取当前线程中实际使用的 sessionId
     */
    public String getCurrentSessionId() {
        String id = CURRENT_SESSION_ID_HOLDER.get();
        CURRENT_SESSION_ID_HOLDER.remove();
        return id;
    }

    public Conversation getSession(String sessionId) {
        if (sessionId == null) return null;
        return sessions.get(sessionId);
    }

    public void endSession(String sessionId) {
        if (sessionId == null) return;
        Conversation removed = sessions.remove(sessionId);
        if (removed != null) {
            System.out.println("结束会话: " + sessionId + "，总对话轮数: " + removed.getTurnCount());
        }
    }

    public void listSessions() {
        System.out.println("=== 活跃会话列表 ===");
        if (sessions.isEmpty()) {
            System.out.println("没有活跃会话");
        } else {
            sessions.forEach((id, conv) -> {
                System.out.printf("会话 ID: %s | 模型：%s | 轮数：%d | tokens: %d%n",
                        id, conv.getModel(), conv.getTurnCount(), conv.getTotalTokens());
            });
        }
        System.out.println("==================");
    }

    /**
     * 获取所有活跃会话（新增）
     */
    public Collection<Conversation> getAllSessions() {
        return sessions.values();
    }
}